{ config, options, lib, ... }:
with lib;
let mkOptionStr = value: mkOption
  { type = types.str;
    default = value; };
in {

  imports = [
    <home-manager/nixos>
    ./desktop
    ./dev
    ./editors
    ./services
    ./shell
  ];

  options = {
    my = {
      username = mkOptionStr "malmgrek";
      email = mkOptionStr "stratos.staboulis@gmail.com";
      home = mkOption {
        type = options.home-manager.users.type.functor.wrapped;
      };
      user = mkOption {
        type = types.submodule;
      };
      packages = mkOption {
        type = with types; listOf package;
      };
      env = mkOption {
        type = with types; attrsOf
          (either (either str path) (listOf (either str path)));
        apply = mapAttrs
          (n: v: if isList v
                 then concatMapStringsSep ":" (x: toString x) v
                 else (toString v));
      };
      alias = mkOption {
        type = with types; nullOr (attrsOf (nullOr (either str path)));
      };
      zsh = {
        rc = mkOption {
          type = types.lines;
          default = "";
          description = ''
            Zsh lines to be written to $XDG_CONFIG_HOME/zsh/extra.zshrc and
            sourced by $XDG_CONFIG_HOME/zsh/.zshrc
          '';
        };
        env = mkOption {
          type = types.lines;
          default = "";
          description = ''
            Zsh lines to be written to $XDG_CONFIG_HOME/zsh/extra.zshenv and
            sourced by $XDG_CONFIG_HOME/zsh/.zshenv
          '';
        };
      };
      i3 = {
        cfg = mkOption {
          type = types.lines;
          default = "";
          description = ''
          i3 configuration lines to be written to $XDG_CONFIG_HOME/i3/config
          '';
        };
      };
    };
  };

  config = {
    ## Convenience aliases
    home-manager.users.${config.my.username} = mkAliasDefinitions options.my.home;

    # Sets my user which is defined in default.nix
    users.users.${config.my.username} = mkAliasDefinitions options.my.user;

    # These packages will be installed only for my user whereas
    # systemPackages will be installed for all users (see Nixos options search
    # and `users.users.<username>.packages`).
    my.user.packages = config.my.packages;

    ## PATH should always start with its old value
    my.env.PATH = [ <bin> "$PATH" ];  # include custom scripts to path
    environment.extraInit =
      let exportLines = mapAttrsToList (n: v: "export ${n}=\"${v}\"") config.my.env;
      in ''
        export XAUTHORITY=/tmp/Xauthority
        [ -e ~/.Xauthority ] && mv -f ~/.Xauthority "$XAUTHORITY"

        ${concatStringsSep "\n" exportLines}
      '';

    # I avoid programs.zsh.*Init variables because they initialize too soon. My
    # zsh config is particular about load order.
    my.home.xdg.configFile = {
      "zsh/extra.zshrc".text =
        let aliasLines = mapAttrsToList (n: v: "alias ${n}=\"${v}\"") config.my.alias;
        in ''
           # This file is autogenerated, do not edit it!
           ${concatStringsSep "\n" aliasLines}
           ${config.my.zsh.rc}
        '';
      "zsh/extra.zshenv".text = ''
        # This file is autogenerated, do not edit it!
        ${config.my.zsh.env};
      '';
    };

    my.home.xdg.configFile."i3/config" = {
      text = ''
        # This file is autogenerated, do not edit it!

        set $mod Mod4

        ${config.my.i3.cfg}
      '';
      recursive = true;
    };
  };

}
