# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "thunderbolt" "nvme" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ "dm-snapshot" "acpi_call" ];
  boot.kernelParams = [ "acpi_backlight=native" ];
  boot.kernelModules = [ "kvm-intel" ];

  # In Lenovo P14s gen 2 (Intel CPU) the network driver AX210 does not work
  # with Linux Kernel 5.10 which is the default in Nixos 21.05. Adding latest
  # kernel version helped getting WiFi to work.
  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.extraModulePackages = with config.boot.kernelPackages; [ acpi_call ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/06453e21-c4bc-4bec-bfaf-54e77e6a8d53";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/F4FB-9887";
      fsType = "vfat";
    };

  boot.initrd.luks.devices = {
    "nixos" = {
      device = "/dev/disk/by-uuid/fe1d5131-3d59-4f8a-96b0-9c85d0bee0d9";
      preLVM = true;
    };
  };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/c13767db-2f81-462d-807b-99025e64dbf8"; }
    ];

  powerManagement = {
    cpuFreqGovernor = lib.mkDefault "powersave";
    powertop.enable = lib.mkDefault true;
  };
  services.tlp = {
    enable = true;
    extraConfig = ''
      START_CHARGE_THRESH_BAT0=75
      STOP_CHARGE_THRESH_BAT0=80

      CPU_SCALING_GOVERNOR_ON_AC=schedutil
      CPU_SCALING_GOVERNOR_ON_BAT=schedutil

      CPU_SCALING_MIN_FREQ_ON_AC=800000
      CPU_SCALING_MAX_FREQ_ON_AC=3500000
      CPU_SCALING_MIN_FREQ_ON_BAT=800000
      CPU_SCALING_MAX_FREQ_ON_BAT=2300000

      # Enable audio power saving for Intel HDA, AC97 devices (timeout in secs).
      # A value of 0 disables, >=1 enables power saving (recommended: 1).
      # Default: 0 (AC), 1 (BAT)
      SOUND_POWER_SAVE_ON_AC=0
      SOUND_POWER_SAVE_ON_BAT=1

      # Runtime Power Management for PCI(e) bus devices: on=disable, auto=enable.
      # Default: on (AC), auto (BAT)
      RUNTIME_PM_ON_AC=on
      RUNTIME_PM_ON_BAT=auto

      # Battery feature drivers: 0=disable, 1=enable
      # Default: 1 (all)
      NATACPI_ENABLE=1
      TPACPI_ENABLE=1
      TPSMAPI_ENABLE=1
    '';
  };

  # high-resolution display
  hardware.video.hidpi.enable = lib.mkDefault true;
}
