theme = "slick"
icons = "awesome"

[[block]]
block = "temperature"
collapsed = false
interval = 10
format = "Min: {min}, Max: {max}, Avg: {average}"
chip = "*-isa-*"

[[block]]
block = "disk_space"
path = "/"
alias = "/"
info_type = "available"
unit = "GB"
interval = 20
warning = 20.0
alert = 10.0

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 5
format = "{percentage}% {time}"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"

[[block]]
block = "networkmanager"
