[icons]
icons = "awesome4"

[theme]
theme = "plain"
[theme.overrides]
idle_bg = "#1d2021"
idle_fg = "#abb2bf"
info_bg = "#1d2021"
info_fg = "#abb2bf"
good_bg = "#1d2021"
good_fg = "#98c379"
warning_bg  = "#1d2021"
warning_fg  = "#e5c07b"
critical_bg = "#1d2021"
critical_fg = "#ff6c6b"
separator = "|"
separator_bg = "#1d2021"
separator_fg = "#4b5263"

[[block]]
block = "xrandr"
format = " $icon $display $resolution "
interval = 10

[[block]]
block = "temperature"
interval = 10
format = " $icon $min - $max, Î¼: $average"
chip = "*-isa-*"

[[block]]
block = "disk_space"
info_type = "available"
alert_unit = "GB"
alert = 10.0
warning = 15.0
format = " $icon $available "
format_alt = " $icon $available / $total "

[[block]]
block = "memory"
format = " $icon $mem_used_percents.eng(w:1) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "
interval = 30
warning_mem = 70
critical_mem = 90

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "keyboard_layout"
driver = "setxkbmap"
interval = 15

[[block]]
block = "backlight"
device = "intel_backlight"

[[block]]
block = "sound"

[[block]]
block = "battery"
interval = 5
format = " $icon $percentage $time"

[[block]]
block = "time"
interval = 60
format = " $icon $timestamp.datetime(f:'%a %Y-%m-%d %R %Z', l:en_US) "

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid $frequency|Wired connection} via $device "
